# API для получения данных о рейсах
api-url: "https://pulkovoairport.ru/api/?col=12&type=departure"

# === НАСТРОЙКИ ГОРОГРАММЫ ===
hologram:
  world: "world"  # Мир, в котором будет голограмма
  x: -66
  y: 156
  z: 170
  update-interval: 60