name: FlightBoard
version: 1.2
main: com.flightboard.FlightBoardPlugin
api-version: 1.20
commands:
  reloadboard:
    description: Reloads the flight board manually
    usage: /reloadboard
    permission: flightboard.reload
permissions:
  flightboard.reload:
    description: Allows reloading the flight board manually
    default: op